#!/bin/zsh

#Inputs 
#(Might be direct filename or path with filename)
INPUT_PARAMETER=$1
INPUT_FILENAME_WITH_EXTENSION=$(basename $INPUT_PARAMETER)
INPUT_FILENAME_WITHOUT_EXTENSION=$(echo $INPUT_FILENAME_WITH_EXTENSION | cut -f 1 -d '.')
INPUT_FOLDER_PATH=$(dirname "$(greadlink -m $INPUT_PARAMETER)")

#Temp/Interim
TEMP_ZIP_FILENAME="$INPUT_FILENAME_WITHOUT_EXTENSION.zip"
TEMP_EXTRACTION_FOLDER_NAME="$INPUT_FILENAME_WITHOUT_EXTENSION-EXTRACTION"
TEMP_EXTRACTION_FOLDER_PATH="$INPUT_FOLDER_PATH/$TEMP_EXTRACTION_FOLDER_NAME"
TEMP_PAYLOAD_FOLDER_PATH="$TEMP_EXTRACTION_FOLDER_PATH/Payload"
TEMP_APP_FOLDER_PATH="$TEMP_PAYLOAD_FOLDER_PATH/$INPUT_FILENAME_WITHOUT_EXTENSION.app"

#Outputs
OUTPUT_PAYLOAD_CONTENTS_FOLDER_PATH="$TEMP_EXTRACTION_FOLDER_PATH/PayloadContents"

#Create a interim copy and make it as a .zip file
cp $INPUT_PARAMETER $TEMP_ZIP_FILENAME

#Extract .ipa(zip) contents to Extraction folder
unzip $TEMP_ZIP_FILENAME -d $TEMP_EXTRACTION_FOLDER_PATH

#Put .app contents to PayloadContents folder
cp -r $TEMP_APP_FOLDER_PATH/. $OUTPUT_PAYLOAD_CONTENTS_FOLDER_PATH

#Clear artifacts
##Clear created interim .zip file
rm $TEMP_ZIP_FILENAME

##Clearing Payload as it is redundant
rm -rf $TEMP_PAYLOAD_FOLDER_PATH